#!/usr/bin/env bash
# process to create an infinite loop and display some messages when receiving different signals

trap "echo I hate the kill command;" SIGTERM
trap " echo Y U no love me?!; exit" SIGINT
trap "rm /var/run/myscript.pid; exit" SIGQUIT SIGTERM

echo $$ > /var/run/myscript.pid

while true; do
	echo "To infinity and beyond"
	sleep 2
done
